repos:
    # github will run `pre-commit run --hook-stage manual -a` and then manually black and flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
        stages: [commit, push, manual]
    -   id: check-json
        stages: [commit, push, manual]
    -   id: end-of-file-fixer
        stages: [commit, push, manual]
    -   id: trailing-whitespace
        stages: [commit, push, manual]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort --profile black
        language: system
        types: [python]
        stages: [commit, push, manual]
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        stages: [commit, push, manual]
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        stages: [commit, push, manual]
    -   id: tests
        name: pytest
        entry: pytest
        pass_filenames: false
        language: system
        types: [python]
        stages: [commit, push, manual]
