language: python
dist: xenial
sudo: true
python:
- 2.7
- 3.7
- 3.6
- 3.5
cache:
  directories:
  - ".cache/pip/"
  - "$HOME/.cache/pip"
  - docs/node_modules/
  - "$HOME/docs/node_modules"
install: pip install -r elastic_panel/test/requirement.txt
script: python setup.py test
deploy:
  provider: pypi
  user: benos
  password:
    secure: Uuhi/6Ml5oJisOl2hqTlw6h0V5ZRU0dmnosxzzzJGNJX7OlX3F3YHXtqE7E+ELiXk5myYsAhfSGmjrIZSiLchaUtvhMgoh4vmBXyNE4iG5L6LkRIuMPpBNKN/agI588MC5XOHe/Bos4CSHOEiUoDbstV9wPTPgk5DMJn/V7PxQA=
  on:
    tags: true
    branch: master
    repo: Benoss/django-elasticsearch-debug-toolbar
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
